### ISSUE TITLE
generic docker version?

### ISSUE THREAD

**Issue by scyto** [sapcc/redfish-certrobot#23]
Hi, i would like to use this with generic docker (so no ironic) with CF DNS Challenge.
(i just have one motherboard at home, i would like to keep a refreshed set of certs on)

Is this team aware of a generic docker version of this project?

**Comment by sandzwerg** [comment]
I'm not aware of something like that, this is specific tailed for our need, which currently means ironic. You might be able to patch this out yourself, but at least for our use case we always need some source of truth where we can look up which nodes to look at. Not sure if @fwiesel knows of something else.

**Comment by fwiesel** [comment]
No, sorry. I am not aware of anything like that. That's why I wrote it in the first place.
